# Generated by Django 5.1.7 on 2025-03-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_externaluser_alter_campaignevent_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='attachments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='envelope_sender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(blank=True),
        ),
    ]
