# Generated by Django 5.1.7 on 2025-03-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailtemplate_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_content',
            field=models.TextField(blank=True),
        ),
    ]
