# Generated by Django 5.1.7 on 2025-03-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailtemplate_plain_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingprofile',
            name='port',
            field=models.IntegerField(default=587),
        ),
    ]
