# Generated by Django 5.1.7 on 2025-03-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_campaign_email_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='clicker_groups',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='submitter_groups',
        ),
        migrations.CreateModel(
            name='CampaignClickerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicker_groups', to='core.campaign')),
                ('group', models.ForeignKey(help_text='Group to add users who click links', on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Clicker Group')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSubmitterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitter_groups', to='core.campaign')),
                ('group', models.ForeignKey(help_text='Group to add users who enter passwords', on_delete=django.db.models.deletion.CASCADE, to='core.group', verbose_name='Submitter Group')),
            ],
        ),
    ]
