# Generated by Django 5.1.7 on 2025-03-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_campaignsubmittergroup_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='send_to_all_users',
            field=models.BooleanField(default=False, help_text='If checked, sends to all ExternalUsers; if unchecked, sends to selected groups'),
        ),
        migrations.CreateModel(
            name='ClickerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='clicker_groups', to='core.externaluser')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='clicker_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups to add users who click links', to='core.clickergroup'),
        ),
        migrations.CreateModel(
            name='SubmitterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='submitter_groups', to='core.externaluser')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='submitter_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups to add users who enter passwords', to='core.submittergroup'),
        ),
        migrations.DeleteModel(
            name='CampaignUserGroup',
        ),
    ]
