# Generated by Django 5.1.7 on 2025-03-31 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_campaign_send_to_all_users_clickergroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='attachments',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='track_activity_duration',
            field=models.PositiveIntegerField(default=3, help_text='Number of days to track user activity after the campaign ends'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_template_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.emailtemplate')),
            ],
        ),
    ]
