# Generated by Django 5.1.7 on 2025-04-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sendingprofile_email_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignevent',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailtemplate'),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.landingpage'),
        ),
        migrations.AddField(
            model_name='sendingprofile',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for API sending.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sendingprofile',
            name='api_provider',
            field=models.CharField(blank=True, choices=[('sendgrid', 'SendGrid')], help_text='API provider (e.g., SendGrid).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sendingprofile',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark as a default profile.'),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='email_headers',
            field=models.JSONField(default=dict, help_text='Additional email headers.'),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='host',
            field=models.CharField(blank=True, help_text='SMTP server host.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='ignore_cert_errors',
            field=models.BooleanField(default=False, help_text='Ignore SMTP cert errors.'),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='interface_type',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('api', 'API')], help_text='SMTP or API.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='name',
            field=models.CharField(help_text='Unique name for this profile.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='password',
            field=models.CharField(blank=True, help_text='SMTP password.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='port',
            field=models.IntegerField(blank=True, help_text='SMTP server port.', null=True),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='smtp_from',
            field=models.CharField(help_text='From email address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sendingprofile',
            name='username',
            field=models.CharField(blank=True, help_text='SMTP username.', max_length=255, null=True),
        ),
    ]
